baseURL = "https://atgreen.github.io/repl-yell/"
languageCode = "en-us"
title = "REPL Yell!"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "Anthony Green"

  [params.label]
    text = "REPL YELL!"
  description = "More More More programming and technology musings"
  env = "production"
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

  [params.homeInfoParams]
    Title = "REPL YELL!"
    Content = "More More More programming and technology musings."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/atgreen"

  [[params.socialIcons]]
    name = "rss"
    url = "/repl-yell/index.xml"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
